"""Katalog over brætspil til dansk spilcafé QR-tracking.

- 100 kuraterede spil i GAMES
- 500 auto-genererede i games_catalog_bulk.py (kør generate_bulk_catalog.py)

Kør scripts/build_game_assets.py for at regenerere seed.sql og wiki_urls.py.
"""

GAMES = [
    {
        "slug": "ticket-to-ride",
        "name": "Ticket to Ride",
        "year": 2004,
        "awards": "Spiel des Jahres 2004 (Tyskland)",
        "fun_fact": "Spillet startede som et jernbane-spil på en ridder-tema prototype — designer Alan R. Moon skiftede til tog, og resten er historie.",
        "wiki": "https://da.wikipedia.org/wiki/Ticket_to_Ride_(spil)",
        "weight": 12,
    },
    {
        "slug": "catan",
        "name": "Catan",
        "year": 1995,
        "awards": "Spiel des Jahres 1995; verdens mest solgte strategispil i mange år",
        "fun_fact": "På Bornholm findes en officiel Catan-udgave med lokale ressourcer — perfekt café-snak mens I bygger veje.",
        "wiki": "https://da.wikipedia.org/wiki/Settlers",
        "weight": 12,
    },
    {
        "slug": "carcassonne",
        "name": "Carcassonne",
        "year": 2000,
        "awards": "Spiel des Jahres 2001; Deutscher Spiele Preis 2000",
        "fun_fact": "Byen Carcassonne i Frankrig har rigtig middelaldermur — mange spillere genkender landskabet fra feriebilleder.",
        "wiki": "https://en.wikipedia.org/wiki/Carcassonne_(board_game)",
        "weight": 10,
    },
    {
        "slug": "azul",
        "name": "Azul",
        "year": 2017,
        "awards": "Spiel des Jahres Kennerspiel 2018",
        "fun_fact": "Fliserne er inspireret af portugisiske azulejos; designer Michael Kiesling ville fange lysrefleksion i keramik.",
        "wiki": "https://en.wikipedia.org/wiki/Azul_(board_game)",
        "weight": 10,
    },
    {
        "slug": "wingspan",
        "name": "Wingspan",
        "year": 2019,
        "awards": "Kennerspiel des Jahres 2020",
        "fun_fact": "Hvert kort har en rigtig fugleart med fakta — mange café-spillere opdager en ny favoritfugl efter første runde.",
        "wiki": "https://en.wikipedia.org/wiki/Wingspan_(board_game)",
        "weight": 9,
    },
    {
        "slug": "7-wonders",
        "name": "7 Wonders",
        "year": 2010,
        "awards": "Kennerspiel des Jahres 2011; Origins Award 2011",
        "fun_fact": "Alle spiller samtidig i tre aldre — derfor føles runden hurtig selv med syv spillere ved ét langt cafébord.",
        "wiki": "https://en.wikipedia.org/wiki/7_Wonders_(board_game)",
        "weight": 9,
    },
    {
        "slug": "splendor",
        "name": "Splendor",
        "year": 2014,
        "awards": "Golden Geek Best Family Game 2014",
        "fun_fact": "Chipsene er tungere end de ser ud — mange grupper laver uofficielle regler om at “klirre” ved køb af ædelsten.",
        "wiki": "https://en.wikipedia.org/wiki/Splendor_(board_game)",
        "weight": 9,
    },
    {
        "slug": "codenames",
        "name": "Codenames",
        "year": 2015,
        "awards": "Spiel des Jahres 2016",
        "fun_fact": "Dansk version findes med danske ord — perfekt til blandede gæstegrupper i et spilcafé.",
        "wiki": "https://en.wikipedia.org/wiki/Codenames_(board_game)",
        "weight": 10,
    },
    {
        "slug": "pandemic",
        "name": "Pandemic",
        "year": 2008,
        "awards": "Z-Man Games; ofte nævnt som gateway kooperativt spil",
        "fun_fact": "Kooperativt design betyder at I vinder eller taber sammen — mindre “take that” ved nabobordet.",
        "wiki": "https://en.wikipedia.org/wiki/Pandemic_(board_game)",
        "weight": 8,
    },
    {
        "slug": "dixit",
        "name": "Dixit",
        "year": 2008,
        "awards": "Spiel des Jahres 2010",
        "fun_fact": "Illustrationerne er bevidst åbne — samme billede kan betyde helt forskellige ting afhængigt af hvem der fortæller.",
        "wiki": "https://en.wikipedia.org/wiki/Dixit_(board_game)",
        "weight": 9,
    },
    {
        "slug": "king-of-tokyo",
        "name": "King of Tokyo",
        "year": 2011,
        "awards": "Gouden Ludo 2012; populær “monster-kamp”-klassiker",
        "fun_fact": "Terninger og kaiju-humor gør det nemt at forklare reglerne på under to minutter ved et cafébord.",
        "wiki": "https://en.wikipedia.org/wiki/King_of_Tokyo",
        "weight": 9,
    },
    {
        "slug": "terraforming-mars",
        "name": "Terraforming Mars",
        "year": 2016,
        "awards": "Kennerspiel des Jahres 2017; Golden Geek 2017",
        "fun_fact": "Korporationsnavnene i spillet er inside-jokes — nørder elsker at spotte referencer mellem runderne.",
        "wiki": "https://en.wikipedia.org/wiki/Terraforming_Mars_(board_game)",
        "weight": 7,
    },
    {
        "slug": "kingdomino",
        "name": "Kingdomino",
        "year": 2016,
        "awards": "Spiel des Jahres 2017",
        "fun_fact": "Domino-princip kombineret med slot-valg — hurtigt at lære, men svært at vinde konsekvent.",
        "wiki": "https://en.wikipedia.org/wiki/Kingdomino",
        "weight": 8,
    },
    {
        "slug": "sushi-go",
        "name": "Sushi Go!",
        "year": 2013,
        "awards": "Golden Geek Best Card Game 2013",
        "fun_fact": "Kortene deles i runde “retter” — mange grupper spiller med lyden “sushi-go” når en runde slutter.",
        "wiki": "https://en.wikipedia.org/wiki/Sushi_Go!",
        "weight": 9,
    },
    {
        "slug": "patchwork",
        "name": "Patchwork",
        "year": 2014,
        "awards": "Spiel des Jahres nomineret; 2-spillers klassiker",
        "fun_fact": "To spillere bygger et tæppe af felter — perfekt til et lille cafébord mens I venter på maden.",
        "wiki": "https://en.wikipedia.org/wiki/Patchwork_(board_game)",
        "weight": 8,
    },
    {
        "slug": "root",
        "name": "Root",
        "year": 2018,
        "awards": "Golden Geek Best Wargame 2018",
        "fun_fact": "Skovdyr med asymmetriske roller — reglerne tager tid, men café-grupper der elsker strategi bliver fanget.",
        "wiki": "https://en.wikipedia.org/wiki/Root_(board_game)",
        "weight": 6,
    },
    {
        "slug": "everdell",
        "name": "Everdell",
        "year": 2018,
        "awards": "Golden Geek Best Board Game 2018",
        "fun_fact": "Det store træ på bordet får ofte komplimenter før første runde — “wow-faktor” ved hylden.",
        "wiki": "https://en.wikipedia.org/wiki/Everdell",
        "weight": 7,
    },
    {
        "slug": "cascadia",
        "name": "Cascadia",
        "year": 2021,
        "awards": "Spiel des Jahres 2022; Kennerspiel 2022",
        "fun_fact": "Vinder kombination af habitat-heks og dyrekort — ofte kaldt “det smukke spil” i spilcaféer.",
        "wiki": "https://en.wikipedia.org/wiki/Cascadia_(board_game)",
        "weight": 8,
    },
    {
        "slug": "exploding-kittens",
        "name": "Exploding Kittens",
        "year": 2015,
        "awards": "Kickstarter-rekord; party-spil",
        "fun_fact": "Startede som en af de mest succesfulde Kickstarter-kampagner nogensinde — nemt at tage frem til en hurtig runde.",
        "wiki": "https://en.wikipedia.org/wiki/Exploding_Kittens",
        "weight": 8,
    },
    {
        "slug": "the-quacks-of-quedlinburg",
        "name": "The Quacks of Quedlinburg",
        "year": 2018,
        "awards": "Kennerspiel des Jahres 2018",
        "fun_fact": "I trækker ingredienser fra en pose — “push your luck” uden at det føles som gambling for nye spillere.",
        "wiki": "https://en.wikipedia.org/wiki/The_Quacks_of_Quedlinburg",
        "weight": 8,
    },
    {
        "slug": "love-letter",
        "name": "Love Letter",
        "year": 2012,
        "awards": "Golden Geek Best Card Game 2012",
        "fun_fact": "Kun 16 kort i bunken — kan spilles overalt, også når caféen er støjende og bordet er småt.",
        "wiki": "https://en.wikipedia.org/wiki/Love_Letter_(card_game)",
        "weight": 7,
    },
    {
        "slug": "scythe",
        "name": "Scythe",
        "year": 2016,
        "awards": "Kennerspiel des Jahres 2017; As d'Or 2017",
        "fun_fact": "Alternativ 1920'er-Europa med mechs og bønder — ofte reserveret til “spilaften”-bordet bagerst i caféen.",
        "wiki": "https://en.wikipedia.org/wiki/Scythe_(board_game)",
        "weight": 6,
    },
    {
        "slug": "klask",
        "name": "Klask",
        "year": 2014,
        "awards": "Dansk design; Brycecorden Games",
        "fun_fact": "Dansk party-klassiker med magnet og disc — larmer lidt, så det er perfekt til livlige spilcafé-aftener.",
        "wiki": "https://da.wikipedia.org/wiki/Klask",
        "weight": 10,
    },
    {
        "slug": "risk",
        "name": "Risk",
        "year": 1957,
        "awards": "Klassisk verdenserobring; mange husker det fra ungdommen",
        "fun_fact": "Et af de ældste mainstream-brætspil — dansk Wikipedia har en artikel under navnet Risk.",
        "wiki": "https://da.wikipedia.org/wiki/Risk",
        "weight": 8,
    },
    {
        "slug": "monopoly",
        "name": "Matador",
        "year": 1936,
        "awards": "Dansk klassiker (Monopoly); C. Drechsler / Brio",
        "fun_fact": "I Danmark kender de fleste det som Matador — samme idé som Monopoly, men med danske gadenavne.",
        "wiki": "https://da.wikipedia.org/wiki/Matador_(br%C3%A6tspil)",
        "weight": 9,
    },
    {
        "slug": "spirit-island",
        "name": "Spirit Island",
        "year": 2017,
        "awards": "Golden Geek Best Cooperative Game 2017",
        "fun_fact": "I spiller som ånder der forsvarer en ø — mange café-grupper elsker at kombinere kræfter mod kolonisterne.",
        "wiki": "https://en.wikipedia.org/wiki/Spirit_Island_(board_game)",
        "weight": 6,
    },
    {
        "slug": "hanabi",
        "name": "Hanabi",
        "year": 2010,
        "awards": "Spiel des Jahres 2013",
        "fun_fact": "I må ikke se egne kort — kommunikation med hints er halvdelen af spillet ved et stille cafébord.",
        "wiki": "https://en.wikipedia.org/wiki/Hanabi_(card_game)",
        "weight": 8,
    },
    {
        "slug": "fluxx",
        "name": "Fluxx",
        "year": 1997,
        "awards": "Mensa Select 1999; kaotiske regler der skifter",
        "fun_fact": "Reglerne ændrer sig midt i spillet — perfekt når gæsterne griner over uventede vendinger.",
        "wiki": "https://en.wikipedia.org/wiki/Fluxx",
        "weight": 6,
    },
    {
        "slug": "uno",
        "name": "UNO",
        "year": 1971,
        "awards": "Verdens mest solgte kortspil; Mattel",
        "fun_fact": "Næsten alle kender en husregel der ikke står i manualen — det er en del af charmen i spilcaféen.",
        "wiki": "https://da.wikipedia.org/wiki/Uno_(kortspil)",
        "weight": 10,
    },
    {
        "slug": "jungle-speed",
        "name": "Jungle Speed",
        "year": 1991,
        "awards": "Party-klassiker; Asmodée",
        "fun_fact": "Totemstaven flyver hen over bordet — caféen bliver højlydt på under et minut.",
        "wiki": "https://en.wikipedia.org/wiki/Jungle_Speed",
        "weight": 9,
    },
    {
        "slug": "one-night-ultimate-werewolf",
        "name": "One Night Ultimate Werewolf",
        "year": 2014,
        "awards": "Party-spil; opfølger til Ultimate Werewolf",
        "fun_fact": "Hele spillet tager én nat — ideelt når I vil have social deduktion uden lang opsætning.",
        "wiki": "https://en.wikipedia.org/wiki/One_Night_Ultimate_Werewolf",
        "weight": 8,
    },
    {
        "slug": "the-resistance",
        "name": "The Resistance",
        "year": 2009,
        "awards": "Golden Geek Best Party Game 2009",
        "fun_fact": "Spioner vs. modstandere uden at nogen dør — bluff og stemmer gør det café-venligt for 5–10 spillere.",
        "wiki": "https://en.wikipedia.org/wiki/The_Resistance_(party_game)",
        "weight": 7,
    },
    {
        "slug": "secret-hitler",
        "name": "Secret Hitler",
        "year": 2016,
        "awards": "Kickstarter-succes; politisk bluff",
        "fun_fact": "Liberaler og fascister skjuler roller — mange grupper spiller det som “den seriøse aften” med snacks.",
        "wiki": "https://en.wikipedia.org/wiki/Secret_Hitler",
        "weight": 6,
    },
    {
        "slug": "coup",
        "name": "Coup",
        "year": 2012,
        "awards": "Populært bluff-kortspil; Indie Boards & Cards",
        "fun_fact": "Kortspil der passer i lommen — ofte taget frem mens I venter på andre gæster ved baren.",
        "wiki": "https://en.wikipedia.org/wiki/Coup_(card_game)",
        "weight": 7,
    },
    {
        "slug": "skull",
        "name": "Skull",
        "year": 2011,
        "awards": "Bluff og bud; oprindeligt offentligt domæne",
        "fun_fact": "Kun få brikker og kopper — men spændingen ved at bluffe føles enorm ved et lille bord.",
        "wiki": "https://en.wikipedia.org/wiki/Skull_(board_game)",
        "weight": 7,
    },
    {
        "slug": "betrayal-at-house-on-the-hill",
        "name": "Betrayal at House on the Hill",
        "year": 2004,
        "awards": "Golden Geek Best Thematic Game 2004",
        "fun_fact": "Huset bygges undervejs — hver session får sin egen “film”-fortælling i caféen.",
        "wiki": "https://en.wikipedia.org/wiki/Betrayal_at_House_on_the_Hill",
        "weight": 7,
    },
    {
        "slug": "small-world",
        "name": "Small World",
        "year": 2009,
        "awards": "Origins Award Best Family Game 2010",
        "fun_fact": "Racer går “in decline” og vælges nye — sjovt at se hvem der dominerer midt i spillet.",
        "wiki": "https://en.wikipedia.org/wiki/Small_World_(board_game)",
        "weight": 7,
    },
    {
        "slug": "dominion",
        "name": "Dominion",
        "year": 2008,
        "awards": "Spiel des Jahres 2009; deck-building-pioner",
        "fun_fact": "Første store deck-building-spil — mange caféer har flere udvidelser på hylden.",
        "wiki": "https://en.wikipedia.org/wiki/Dominion_(card_game)",
        "weight": 7,
    },
    {
        "slug": "7-wonders-duel",
        "name": "7 Wonders Duel",
        "year": 2015,
        "awards": "Kennerspiel des Jahres 2016",
        "fun_fact": "Tilpasset to spillere med militær, videnskab og wonder-tracks — fast 2-personers bord i caféen.",
        "wiki": "https://en.wikipedia.org/wiki/7_Wonders_Duel",
        "weight": 8,
    },
    {
        "slug": "jaipur",
        "name": "Jaipur",
        "year": 2009,
        "awards": "Golden Geek Best 2-Player Board Game 2010",
        "fun_fact": "Handel med kamel, juveler og tekstil på under 30 minutter — klassisk “date night”-spil.",
        "wiki": "https://en.wikipedia.org/wiki/Jaipur_(board_game)",
        "weight": 8,
    },
    {
        "slug": "lost-cities",
        "name": "Lost Cities",
        "year": 1999,
        "awards": "Spiel des Jahres nomineret; 2-spillers Reiner Knizia",
        "fun_fact": "Kortstakke der vokser som ekspeditioner — let at lære, svært at lægge perfekt.",
        "wiki": "https://en.wikipedia.org/wiki/Lost_Cities",
        "weight": 7,
    },
    {
        "slug": "hive",
        "name": "Hive",
        "year": 2001,
        "awards": "Mensa Select 2006; brikspil uden bræt",
        "fun_fact": "Ingen bræt — kun brikker der klatrer. Perfekt på små caféborde med kaffe.",
        "wiki": "https://en.wikipedia.org/wiki/Hive_(game)",
        "weight": 7,
    },
    {
        "slug": "onitama",
        "name": "Onitama",
        "year": 2014,
        "awards": "Abstract 2-spillers; bevægelseskort skifter",
        "fun_fact": "Som skak med skiftende bevægelser — en runde tager ofte under 20 minutter.",
        "wiki": "https://en.wikipedia.org/wiki/Onitama",
        "weight": 7,
    },
    {
        "slug": "santorini",
        "name": "Santorini",
        "year": 2017,
        "awards": "Golden Geek Best Abstract Game 2017",
        "fun_fact": "Byg tårne på en ø — guder-kortene giver uventede twists selv for erfarne spillere.",
        "wiki": "https://en.wikipedia.org/wiki/Santorini_(board_game)",
        "weight": 7,
    },
    {
        "slug": "telestrations",
        "name": "Telestrations",
        "year": 2009,
        "awards": "Party-klassiker; tegn og gæt-kæde",
        "fun_fact": "Dårlige tegninger er pointen — caféen griner højlydt når “kat” bliver til “raket”.",
        "wiki": "https://en.wikipedia.org/wiki/Telestrations",
        "weight": 8,
    },
    {
        "slug": "just-one",
        "name": "Just One",
        "year": 2018,
        "awards": "Spiel des Jahres 2019",
        "fun_fact": "Alle skriver ét hint — duplikater slettes. Samarbejde uden at det føles tungt.",
        "wiki": "https://en.wikipedia.org/wiki/Just_One_(board_game)",
        "weight": 9,
    },
    {
        "slug": "decrypto",
        "name": "Decrypto",
        "year": 2018,
        "awards": "Party-spil; kodeknækning mellem hold",
        "fun_fact": "Hold sender kodede beskeder — modstanderen lytter med og prøver at knække mønsteret.",
        "wiki": "https://en.wikipedia.org/wiki/Decrypto",
        "weight": 7,
    },
    {
        "slug": "the-mind",
        "name": "The Mind",
        "year": 2018,
        "awards": "Spiel des Jahres nomineret; kooperativt kortspil",
        "fun_fact": "Ingen snak — kun timing og øjenkontakt. Stilleste (eller mest anspændte) bord i caféen.",
        "wiki": "https://en.wikipedia.org/wiki/The_Mind_(card_game)",
        "weight": 8,
    },
    {
        "slug": "no-thanks",
        "name": "No Thanks!",
        "year": 2004,
        "awards": "Klassisk “push your luck”; Goliath / Amigo",
        "fun_fact": "Afvis kort med chips — den der har lavest total vinder. Hurtig filler mellem retter.",
        "wiki": "https://en.wikipedia.org/wiki/No_Thanks!_(card_game)",
        "weight": 7,
    },
    {
        "slug": "diamant",
        "name": "Diamant",
        "year": 2005,
        "awards": "Spiel des Jahres nomineret (som Incan Gold)",
        "fun_fact": "Gå dybere i hulen eller vend hjem — samme spil som Incan Gold med andet tema.",
        "wiki": "https://en.wikipedia.org/wiki/Incan_Gold",
        "weight": 7,
    },
    {
        "slug": "camel-up",
        "name": "Camel Up",
        "year": 2014,
        "awards": "Spiel des Jahres 2014",
        "fun_fact": "Kameler stables og væddes på — pyramiden med terninger er et lille showpiece på bordet.",
        "wiki": "https://en.wikipedia.org/wiki/Camel_Up",
        "weight": 8,
    },
    {
        "slug": "colt-express",
        "name": "Colt Express",
        "year": 2014,
        "awards": "As d'Or 2015; Spiel des Jahres 2015",
        "fun_fact": "Programmer handlinger i et tog — den 3D-togbane får ofte fotos fra gæster.",
        "wiki": "https://en.wikipedia.org/wiki/Colt_Express",
        "weight": 8,
    },
    {
        "slug": "qwirkle",
        "name": "Qwirkle",
        "year": 2006,
        "awards": "Spiel des Jahres 2011; Mensa Select",
        "fun_fact": "Farver og former i rækker — børn og voksne kan sidde ved samme cafébord.",
        "wiki": "https://en.wikipedia.org/wiki/Qwirkle",
        "weight": 8,
    },
    {
        "slug": "blokus",
        "name": "Blokus",
        "year": 2000,
        "awards": "Mensa Select 2004; tetris-lignende placering",
        "fun_fact": "Fyld brættet med dine brikker — sidste brikker er ofte umulige og giver god debat.",
        "wiki": "https://en.wikipedia.org/wiki/Blokus",
        "weight": 7,
    },
    {
        "slug": "parks",
        "name": "PARKS",
        "year": 2019,
        "awards": "Golden Geek Best Thematic Game 2019",
        "fun_fact": "Besøg amerikanske nationalparker med smukke illustrationer — hyggespil med vandringstema.",
        "wiki": "https://en.wikipedia.org/wiki/Parks_(board_game)",
        "weight": 7,
    },
    {
        "slug": "ark-nova",
        "name": "Ark Nova",
        "year": 2021,
        "awards": "Golden Geek Best Heavy Strategy 2021",
        "fun_fact": "Byg et moderne zoo med kort og dyr — populært blandt strategi-gæster der booker lange sessioner.",
        "wiki": "https://en.wikipedia.org/wiki/Ark_Nova",
        "weight": 5,
    },
    {
        "slug": "stone-age",
        "name": "Stone Age",
        "year": 2008,
        "awards": "Deutscher Spiele Preis 2008; worker placement-klassiker",
        "fun_fact": "Terninger bestemmer ressourcer — mange husker “brød”-reglen fra deres første café-aften.",
        "wiki": "https://en.wikipedia.org/wiki/Stone_Age_(board_game)",
        "weight": 7,
    },
    {
        "slug": "lords-of-waterdeep",
        "name": "Lords of Waterdeep",
        "year": 2012,
        "awards": "Golden Geek Best Strategy Game 2012",
        "fun_fact": "Dungeons & Dragons-byen som arbejdsplads — quest-brikker gør worker placement let at forklare.",
        "wiki": "https://en.wikipedia.org/wiki/Lords_of_Waterdeep",
        "weight": 7,
    },
    {
        "slug": "castles-of-burgundy",
        "name": "The Castles of Burgundy",
        "year": 2011,
        "awards": "Golden Geek Best Strategy Game 2011",
        "fun_fact": "Terninger og felter i ren strategi — elsket af spillere der vil have “én mere runde”.",
        "wiki": "https://en.wikipedia.org/wiki/The_Castles_of_Burgundy",
        "weight": 6,
    },
    {
        "slug": "heat-pedal-to-the-metal",
        "name": "Heat: Pedal to the Metal",
        "year": 2022,
        "awards": "Golden Geek Best Racing Game 2023",
        "fun_fact": "Formel 1 med håndstyring af hastighed — adrenalinfyldt uden at være et videospil.",
        "wiki": "https://en.wikipedia.org/wiki/Heat:_Pedal_to_the_Metal",
        "weight": 7,
    },
    {
        "slug": "brass-birmingham",
        "name": "Brass: Birmingham",
        "year": 2018,
        "awards": "Golden Geek Best Heavy Strategy 2018",
        "fun_fact": "Industrielt England på bræt — ofte reserveret til erfarne gæster der vil have en hel eftermiddag.",
        "wiki": "https://en.wikipedia.org/wiki/Brass:_Birmingham",
        "weight": 4,
    },
    {
        "slug": "blood-rage",
        "name": "Blood Rage",
        "year": 2015,
        "awards": "Golden Geek Best Thematic Game 2015",
        "fun_fact": "Vikinger og Ragnarok med miniatyrer — draft og kamp i samme kasse.",
        "wiki": "https://en.wikipedia.org/wiki/Blood_Rage_(board_game)",
        "weight": 6,
    },
    {
        "slug": "power-grid",
        "name": "Power Grid",
        "year": 2004,
        "awards": "Deutscher Spiele Preis 2005; økonomi og netværk",
        "fun_fact": "Auktioner om kraftværker — turn order drejer om, så den der ligger sidst ofte vinder bud.",
        "wiki": "https://en.wikipedia.org/wiki/Power_Grid",
        "weight": 6,
    },
    {
        "slug": "race-for-the-galaxy",
        "name": "Race for the Galaxy",
        "year": 2007,
        "awards": "Golden Geek Best Card Game 2008",
        "fun_fact": "Ikoner i stedet for lang tekst — når I kan symbolerne, går runder lynhurtigt.",
        "wiki": "https://en.wikipedia.org/wiki/Race_for_the_Galaxy",
        "weight": 6,
    },
    {
        "slug": "the-crew",
        "name": "The Crew: The Quest for Planet Nine",
        "year": 2019,
        "awards": "Kennerspiel des Jahres 2020; kooperativt trick-taking",
        "fun_fact": "50 missioner med stigende sværhedsgrad — perfekt til faste stamkunder i caféen.",
        "wiki": "https://en.wikipedia.org/wiki/The_Crew_(card_game)",
        "weight": 8,
    },
    {
        "slug": "rhino-hero",
        "name": "Rhino Hero",
        "year": 2011,
        "awards": "Kinderspiel des Jahres nomineret; stabling",
        "fun_fact": "Et korttårn der vakler — børnefamilier og voksne spiller det med samme grin.",
        "wiki": "https://en.wikipedia.org/wiki/Rhino_Hero",
        "weight": 7,
    },
    {
        "slug": "timeline",
        "name": "Timeline",
        "year": 2010,
        "awards": "Party / læring; Asmodeée",
        "fun_fact": "Placer begivenheder i rækkefølge — I lærer ofte en mærkelig historiefact undervejs.",
        "wiki": "https://en.wikipedia.org/wiki/Timeline_(card_game)",
        "weight": 7,
    },
    {
        "slug": "hitster",
        "name": "Hitster",
        "year": 2022,
        "awards": "Party-spil med musik; Jumbo",
        "fun_fact": "Gæt årstallet for hits — mange caféer spiller det med højtaler fra gæsternes playliste.",
        "wiki": "https://en.wikipedia.org/wiki/Hitster",
        "weight": 8,
    },
    {
        "slug": "so-clover",
        "name": "So Clover!",
        "year": 2021,
        "awards": "Party; ordforbindelser på tavle",
        "fun_fact": "Skriv hemmelige ord der binder fire sammen — samarbejde med masser af “aha!”-øjeblikke.",
        "wiki": "https://en.wikipedia.org/wiki/So_Clover!",
        "weight": 7,
    },
    {
        "slug": "scout",
        "name": "Scout",
        "year": 2021,
        "awards": "Spiel des Jahres nomineret; kortstakke og bud",
        "fun_fact": "Vend kortstakke for at byde — reglerne er få, men dybden vokser efter ti minutter.",
        "wiki": "https://en.wikipedia.org/wiki/Scout_(card_game)",
        "weight": 7,
    },
    {
        "slug": "forbidden-island",
        "name": "Forbidden Island",
        "year": 2010,
        "awards": "Gateway kooperativt; Matt Leacock",
        "fun_fact": "Øen synker mens I samler skatte — lettere indgang end Pandemic for nye spillere.",
        "wiki": "https://en.wikipedia.org/wiki/Forbidden_Island",
        "weight": 7,
    },
    {
        "slug": "forbidden-desert",
        "name": "Forbidden Desert",
        "year": 2013,
        "awards": "Opfølger til Forbidden Island",
        "fun_fact": "Sandstorm og flyvende deler — kooperativt med mere “action” end den første ø.",
        "wiki": "https://en.wikipedia.org/wiki/Forbidden_Desert",
        "weight": 7,
    },
    {
        "slug": "flash-point-fire-rescue",
        "name": "Flash Point: Fire Rescue",
        "year": 2011,
        "awards": "Golden Geek Best Thematic Game 2012",
        "fun_fact": "Sluk brand og red mennesker — terninger og røg gør hver redning dramatisk.",
        "wiki": "https://en.wikipedia.org/wiki/Flash_Point:_Fire_Rescue",
        "weight": 7,
    },
    {
        "slug": "mysterium",
        "name": "Mysterium",
        "year": 2015,
        "awards": "Golden Geek Best Party Game 2016",
        "fun_fact": "Én spiller er spøgelse med billedkort — resten gætter mordet som et spøgelses-Cluedo.",
        "wiki": "https://en.wikipedia.org/wiki/Mysterium_(board_game)",
        "weight": 7,
    },
    {
        "slug": "dead-of-winter",
        "name": "Dead of Winter",
        "year": 2014,
        "awards": "Golden Geek Best Thematic Game 2014",
        "fun_fact": "Zombie-overlevelse med skjulte mål — nogen i gruppen lyver måske om intentioner.",
        "wiki": "https://en.wikipedia.org/wiki/Dead_of_Winter:_A_Crossroads_Game",
        "weight": 6,
    },
    {
        "slug": "bang-the-dice-game",
        "name": "Bang! The Dice Game",
        "year": 2013,
        "awards": "Vesterligen tema; terning-variant af Bang!",
        "fun_fact": "Sherif, banditter og Renegade med terninger — hurtigere end originalen til en café-runde.",
        "wiki": "https://en.wikipedia.org/wiki/Bang!_(card_game)",
        "weight": 7,
    },
    {
        "slug": "clank",
        "name": "Clank!",
        "year": 2016,
        "awards": "Golden Geek Best Family Game 2017",
        "fun_fact": "Støj vækker dragen — deck-building i en dungeon med humor og risiko.",
        "wiki": "https://en.wikipedia.org/wiki/Clank!_A_Deck-Building_Adventure",
        "weight": 7,
    },
    {
        "slug": "quest-for-el-dorado",
        "name": "The Quest for El Dorado",
        "year": 2017,
        "awards": "Spiel des Jahres 2017 nomineret; deck-building race",
        "fun_fact": "Reiner Knizia kombinerer deck-building med løb — let at lære for familier.",
        "wiki": "https://en.wikipedia.org/wiki/The_Quest_for_El_Dorado",
        "weight": 7,
    },
    {
        "slug": "gloomhaven-jaws-of-the-lion",
        "name": "Gloomhaven: Jaws of the Lion",
        "year": 2020,
        "awards": "Golden Geek Best Thematic Game 2020",
        "fun_fact": "Kortere kampagne end Gloomhaven — mange caféer bruger den som “vi spiller det her fredag”.",
        "wiki": "https://en.wikipedia.org/wiki/Gloomhaven",
        "weight": 5,
    },
    {
        "slug": "monopoly-deal",
        "name": "Monopoly Deal",
        "year": 2008,
        "awards": "Hurtig kortversion af Matador/Monopoly",
        "fun_fact": "Fuldfør tre ejendomssæt med kort — Matador-fans får deres fix på 15 minutter.",
        "wiki": "https://en.wikipedia.org/wiki/Monopoly_Deal",
        "weight": 8,
    },
    {
        "slug": "scrabble",
        "name": "Scrabble",
        "year": 1938,
        "awards": "Klassisk ordspil; Hasbro / Mattel",
        "fun_fact": "Dansk udgave findes — café-gæster diskuterer ofte om fremmedord må bruges.",
        "wiki": "https://da.wikipedia.org/wiki/Scrabble",
        "weight": 8,
    },
    {
        "slug": "cluedo",
        "name": "Cluedo",
        "year": 1949,
        "awards": "Klassisk detektivspil; Hasbro",
        "fun_fact": "Hvem, hvor og med hvad — mange kender karaktererne fra barndommen før første café-besøg.",
        "wiki": "https://da.wikipedia.org/wiki/Cluedo",
        "weight": 8,
    },
    {
        "slug": "backgammon",
        "name": "Backgammon",
        "year": -3000,
        "awards": "Et af verdens ældste spil; klassiker",
        "fun_fact": "Terninger og dobbeltsten — nogle caféer har et fast bræt ved vinduet til stamspillere.",
        "wiki": "https://da.wikipedia.org/wiki/Backgammon",
        "weight": 7,
    },
    {
        "slug": "sequence",
        "name": "Sequence",
        "year": 1982,
        "awards": "Familie-klassiker; Jax Ltd",
        "fun_fact": "Fire på stribe med kort og jetoner — nemt at blande hold på et langt cafébord.",
        "wiki": "https://en.wikipedia.org/wiki/Sequence_(game)",
        "weight": 7,
    },
    {
        "slug": "abalone",
        "name": "Abalone",
        "year": 1987,
        "awards": "Mensa Select; strategisk 2-spillers",
        "fun_fact": "Skub kugler i seks retninger — føles som skak med fysiske kugler der ruller.",
        "wiki": "https://en.wikipedia.org/wiki/Abalone_(board_game)",
        "weight": 6,
    },
    {
        "slug": "pentago",
        "name": "Pentago",
        "year": 2004,
        "awards": "Svensk design; drejende felter",
        "fun_fact": "Fem på stribe — men feltet drejes efter hvert træk, så planen ændrer sig konstant.",
        "wiki": "https://en.wikipedia.org/wiki/Pentago",
        "weight": 6,
    },
    {
        "slug": "werewolf",
        "name": "Werewolf",
        "year": 1986,
        "awards": "Klassisk social deduktion; Mafia-variant",
        "fun_fact": "Ingen bræt — kun stemmer og roller. Stadig populært til store grupper i spilcaféer.",
        "wiki": "https://en.wikipedia.org/wiki/Mafia_(party_game)",
        "weight": 7,
    },
    {
        "slug": "taboo",
        "name": "Taboo",
        "year": 1989,
        "awards": "Party-klassiker; Hasbro",
        "fun_fact": "Forklar ord uden forbudte termer — buzzeren på bordet skaber øjeblikkelig stemning.",
        "wiki": "https://en.wikipedia.org/wiki/Taboo_(game)",
        "weight": 8,
    },
    {
        "slug": "sushi-go-party",
        "name": "Sushi Go Party!",
        "year": 2016,
        "awards": "Udvidet version af Sushi Go!; op til 8 spillere",
        "fun_fact": "Konfigurerbar menu med retter — caféen kan vælge “hurtig” eller “kaotisk” opsætning.",
        "wiki": "https://en.wikipedia.org/wiki/Sushi_Go!",
        "weight": 8,
    },
    {
        "slug": "werewords",
        "name": "Werewords",
        "year": 2017,
        "awards": "Party; fra skaberen af One Night Werewolf",
        "fun_fact": "Ordet skal gættes — men ulvene kender det hemmelige ord og saboterer.",
        "wiki": "https://en.wikipedia.org/wiki/Werewords",
        "weight": 7,
    },
    {
        "slug": "wavelength",
        "name": "Wavelength",
        "year": 2019,
        "awards": "Party; skala og gæt",
        "fun_fact": "Én spiller kender et hemmeligt punkt på en skala — resten diskuterer sig frem.",
        "wiki": "https://en.wikipedia.org/wiki/Wavelength_(party_game)",
        "weight": 7,
    },
    {
        "slug": "cartographers",
        "name": "Cartographers",
        "year": 2019,
        "awards": "Golden Geek Best Print & Play 2019; flip-and-write",
        "fun_fact": "Tegn kort på et ark mens mål skifter — alle spiller samtidig uden at vente på tur.",
        "wiki": "https://en.wikipedia.org/wiki/Cartographers_(board_game)",
        "weight": 7,
    },
    {
        "slug": "viticulture",
        "name": "Viticulture",
        "year": 2013,
        "awards": "Golden Geek Best Strategy 2015 (Essential Edition)",
        "fun_fact": "Byg en vingård i Toscana — arbejdere og vinhøst giver hyggelig café-atmosfære.",
        "wiki": "https://en.wikipedia.org/wiki/Viticulture_(board_game)",
        "weight": 6,
    },
    {
        "slug": "tapestry",
        "name": "Tapestry",
        "year": 2019,
        "awards": "Civilisations-opbygning; Stonemaier Games",
        "fun_fact": "Fire civilisationer over flere tidsaldre — “én sidste runde” fylder ofte hele aftenen.",
        "wiki": "https://en.wikipedia.org/wiki/Tapestry_(board_game)",
        "weight": 5,
    },
    {
        "slug": "star-realms",
        "name": "Star Realms",
        "year": 2014,
        "awards": "Golden Geek Best Card Game 2014",
        "fun_fact": "Sci-fi deck-building duel — hurtige kampe mellem to gæster ved baren.",
        "wiki": "https://en.wikipedia.org/wiki/Star_Realms",
        "weight": 7,
    },
    {
        "slug": "marvel-champions",
        "name": "Marvel Champions",
        "year": 2020,
        "awards": "LCG kooperativt; Fantasy Flight",
        "fun_fact": "Spil som helte mod skurke — mange café-gæster vælger deres favorit-Marvel-figur.",
        "wiki": "https://en.wikipedia.org/wiki/Marvel_Champions",
        "weight": 6,
    },
    {
        "slug": "flip-7",
        "name": "Flip 7",
        "year": 2024,
        "awards": "Party; push your luck med kort",
        "fun_fact": "Saml unikke tal uden at buste — ny hit der ofte kommer på “hvad er det der grønne spil?”-hylden.",
        "wiki": "https://en.wikipedia.org/wiki/Flip_7",
        "weight": 8,
    },
    {
        "slug": "calico",
        "name": "Calico",
        "year": 2020,
        "awards": "Golden Geek Best Abstract 2021",
        "fun_fact": "Sy et tæppe af farvede lapper — katte-mål gør det sødt uden at være et børnespil.",
        "wiki": "https://en.wikipedia.org/wiki/Calico_(board_game)",
        "weight": 7,
    },
    {
        "slug": "planet",
        "name": "Planet",
        "year": 2019,
        "awards": "Spiel des Jahres 2019; 3D-dodekaeder",
        "fun_fact": "Hver spiller har sin egen lille planet — magnetiske felter giver wow ved første opsætning.",
        "wiki": "https://en.wikipedia.org/wiki/Planet_(board_game)",
        "weight": 7,
    },
    {
        "slug": "my-little-scythe",
        "name": "My Little Scythe",
        "year": 2017,
        "awards": "Familie-version inspireret af Scythe",
        "fun_fact": "Søde dyr i en konkurrence om tærter — gateway til Scythe-universet for yngre spillere.",
        "wiki": "https://en.wikipedia.org/wiki/My_Little_Scythe",
        "weight": 7,
    },
]
